<?php
/**
 * ModelInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Towoju5\MonoCards\Model
 * @author   Emmanuel A Towoju
 * @link     https://towoju.com.ng
 */

/**
 * Zeenah Virtual Card
 *
 * No description provided (generated by Swagger Codegen https://towoju.com.ng)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://towoju.com.ng.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://towoju.com.ng
 * Do not edit the class manually.
 */

namespace Towoju5\MonoCards\Model;

/**
 * Interface abstracting model access.
 *
 * @package Towoju5\MonoCards\Model
 * @author  Emmanuel A Towoju
 */
interface ModelInterface
{
    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName();

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes();

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats();

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     *
     * @return array
     */
    public static function attributeMap();

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters();

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters();

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array
     */
    public function listInvalidProperties();

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool
     */
    public function valid();
}
