<?php
/**
 * UpdateCardPinRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Towoju5\MonoCards
 * @author   Emmanuel A Towoju
 * @link     https://towoju.com.ng
 */

/**
 * Zeenah Virtual Card
 *
 * No description provided (generated by Swagger Codegen https://towoju.com.ng)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://towoju.com.ng.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://towoju.com.ng
 * Please update the test case below to test the model.
 */

namespace Towoju5\MonoCards;

/**
 * UpdateCardPinRequestTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateCardPinRequest
 * @package     Towoju5\MonoCards
 * @author      Emmanuel A Towoju
 * @link        https://towoju.com.ng
 */
class UpdateCardPinRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateCardPinRequest"
     */
    public function testUpdateCardPinRequest()
    {
    }

    /**
     * Test attribute "old_pin"
     */
    public function testPropertyOldPin()
    {
    }

    /**
     * Test attribute "new_pin"
     */
    public function testPropertyNewPin()
    {
    }
}
