<?php
/**
 * MiscApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Towoju5\MonoCards
 * @author   Emmanuel A Towoju
 * @link     https://towoju.com.ng
 */

/**
 * Zeenah Virtual Card
 *
 * No description provided (generated by Swagger Codegen https://towoju.com.ng)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://towoju.com.ng.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://towoju.com.ng
 * Please update the test case below to test the endpoint.
 */

namespace Towoju5\MonoCards;

use Towoju5\MonoCards\Configuration;
use Towoju5\MonoCards\ApiException;
use Towoju5\MonoCards\ObjectSerializer;

/**
 * MiscApiTest Class Doc Comment
 *
 * @category Class
 * @package  Towoju5\MonoCards
 * @author   Emmanuel A Towoju
 * @link     https://towoju.com.ng
 */
class MiscApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createaVirtualCard
     *
     * Create a Virtual Card.
     *
     */
    public function testCreateaVirtualCard()
    {
    }

    /**
     * Test case for fetchCardDetails
     *
     * Fetch Card Details.
     *
     */
    public function testFetchCardDetails()
    {
    }

    /**
     * Test case for fetchCardTransactions
     *
     * Fetch Card Transactions.
     *
     */
    public function testFetchCardTransactions()
    {
    }

    /**
     * Test case for freezeaCard
     *
     * Freeze a Card.
     *
     */
    public function testFreezeaCard()
    {
    }

    /**
     * Test case for fundaVirtualCard
     *
     * Fund a Virtual Card.
     *
     */
    public function testFundaVirtualCard()
    {
    }

    /**
     * Test case for liquidateCardBalance
     *
     * Liquidate Card Balance.
     *
     */
    public function testLiquidateCardBalance()
    {
    }

    /**
     * Test case for unfreezeaCard
     *
     * Unfreeze a Card.
     *
     */
    public function testUnfreezeaCard()
    {
    }

    /**
     * Test case for updateCardPin
     *
     * Update Card Pin.
     *
     */
    public function testUpdateCardPin()
    {
    }
}
